# Generated by Django 3.2 on 2021-08-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210827_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_name',
            field=models.CharField(default='M', max_length=100),
            preserve_default=False,
        ),
    ]
